import { Injectable } from '@nestjs/common';
import { AGENT_DEFINITIONS, CONTRACT_VERSION, ORCHESTRATOR_VERSION } from '@trialguard/agents';
import PDFDocument from 'pdfkit';
import { hashObject, sha256Hex } from '../common/canonical-json';
import { notFound } from '../common/errors';
import { ONTOLOGY_VERSION } from '../ontology/dictionary';
import { PrismaService } from '../prisma/prisma.service';
import { RULE_ENGINE_VERSION } from '../rule-engine/evaluator';
import { StorageService } from '../storage/storage.service';
import { AuditService } from './audit.service';

export const DOSSIER_SERVICE_VERSION = '1.0.0';

/** Standard PDF fonts are WinAnsi-encoded: map symbols they cannot render. */
export function pdfSafe(v: unknown): string {
  return String(v ?? '')
    .replace(/→/g, '->')
    .replace(/[−–—]/g, '-')
    .replace(/≠/g, '!=')
    .replace(/≥/g, '>=')
    .replace(/≤/g, '<=')
    .replace(/…/g, '...')
    .replace(/[“”]/g, '"')
    .replace(/[‘’]/g, "'")
    .replace(/Δ/g, 'delta')
    .replace(/[^\x09\x0A\x0D\x20-\x7E\u00A0-\u00FF\u2022]/g, '?');
}

const criterionOrder = (k: string) => (k.startsWith('INC') ? 0 : k.startsWith('EXC') ? 1 : 2) * 1000 + Number(k.slice(4));

export const DISCLAIMER =
  'FDA-style audit dossier generated by TrialGuard AI, a hackathon demonstration system operating on SYNTHETIC clinical data. ' +
  'It implements Part-11-oriented audit controls (attributable, time-stamped, append-only, hash-chained records) but is NOT FDA approved, ' +
  'NOT validated for 21 CFR Part 11 compliance, NOT clinically validated, and NOT suitable for direct clinical decision-making. ' +
  'Eligibility outcomes are produced by a deterministic rule engine; AI agents only extract and summarise, and all ambiguous cases require qualified human review.';

type Dossier = Awaited<ReturnType<DossierService['buildJson']>>;

@Injectable()
export class DossierService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly audit: AuditService,
    private readonly storage: StorageService,
  ) {}

  async buildJson(screeningId: string) {
    const s = await this.prisma.screening.findUnique({
      where: { id: screeningId },
      include: {
        trial: true,
        protocolVersion: { include: { criteria: true } },
        patient: true,
        patientVersion: true,
        evaluations: { orderBy: { criterionKey: 'asc' } },
        flags: { orderBy: { createdAt: 'asc' } },
        reviewTasks: { include: { decisions: { include: { reviewer: { select: { displayName: true, email: true } } }, orderBy: { createdAt: 'asc' } } } },
        executions: { orderBy: { startedAt: 'asc' } },
      },
    });
    if (!s) throw notFound('Screening');
    const events = await this.audit.events(screeningId);
    const verification = await this.audit.verify(screeningId);
    const protocolRoot = await this.audit.latestRoot(`protocol:${s.protocolVersionId}`);
    const patientRoot = await this.audit.latestRoot(`patient:${s.patientVersionId}`);
    const upstream = await this.prisma.lyzrExecution.findMany({ where: { id: { in: [s.protocolVersion.agentExecutionId, s.patientVersion.agentExecutionId].filter((x): x is string => !!x) } } });
    const executions = [...upstream, ...s.executions];
    const narrative = s.narrative as { narrative?: { summary: string; keyPoints: string[] }; source?: string } | null;
    const phi = (s.patientVersion.phiSummary ?? { totalRedactions: 0, byCategory: {} }) as { totalRedactions: number; byCategory: Record<string, number> };
    const reviewDecisions = s.reviewTasks.flatMap((t) => t.decisions);

    return {
      dossierType: 'FDA-style audit dossier — Part-11-oriented audit controls (SYNTHETIC DEMONSTRATION)',
      generatedAt: new Date().toISOString(),
      generator: { component: 'dossier-service', version: DOSSIER_SERVICE_VERSION },
      synthetic: true,
      trial: { code: s.trial.code, title: s.trial.title, phase: s.trial.phase, sponsor: s.trial.sponsor, indication: s.trial.indication },
      protocol: {
        versionId: s.protocolVersionId,
        version: s.protocolVersion.version,
        contentHash: s.protocolVersion.contentHash,
        redactedHash: s.protocolVersion.redactedHash,
        pages: s.protocolVersion.pageCount,
        criteria: s.protocolVersion.criteria.length,
        ambiguousCriteria: s.protocolVersion.criteria.filter((c) => c.ambiguity === 1).map((c) => c.criterionKey),
        extractionAuditRoot: protocolRoot?.rootHash ?? null,
        crossValidation: s.protocolVersion.crossValidation ?? null,
      },
      patient: {
        patientRef: s.patient.patientRef,
        versionNumber: s.patientVersion.versionNumber,
        snapshotHash: s.patientVersion.snapshotHash,
        extractionAuditRoot: patientRoot?.rootHash ?? null,
        crossValidation: s.patientVersion.crossValidation ?? null,
      },
      phiRedaction: {
        confirmed: true,
        statement:
          'All documents were PHI-redacted by the application before any agent inference. Only deterministic aliases were sent to agents. The encrypted alias vault is never exported, logged, or sent to Lyzr/AIMS, and is excluded from this dossier.',
        totalRedactions: phi.totalRedactions,
        byCategory: phi.byCategory,
      },
      screening: {
        id: s.id,
        ref: s.screeningRef,
        screeningDate: s.screeningDate,
        status: s.status,
        createdAt: s.createdAt.toISOString(),
        completedAt: s.completedAt?.toISOString() ?? null,
        durationMs: s.durationMs,
      },
      decision: {
        systemDecision: s.decision,
        finalDecision: s.finalDecision ?? s.decision,
        decidedBy: s.finalDecision ? 'qualified human reviewer (system decision retained unchanged)' : `deterministic rule engine v${RULE_ENGINE_VERSION}`,
        confidence: s.confidence,
        confidencePct: s.confidence === null ? null : Math.round(s.confidence * 1000) / 10,
        reasons: s.decisionReasons,
        confidenceBreakdown: s.confidenceBreakdown,
      },
      criterionEvaluations: [...s.evaluations].sort((a, b) => criterionOrder(a.criterionKey) - criterionOrder(b.criterionKey)).map((e) => ({
        criterionId: e.criterionKey,
        category: e.category,
        mandatory: e.mandatory,
        requirement: e.requirement,
        operator: e.operator,
        expectedValue: e.expectedValue,
        actualValue: e.actualValue,
        ruleExpression: e.ruleExpression,
        result: e.result,
        reason: e.reason,
        confidence: e.confidence,
        protocolSource: { page: e.sourcePage, section: e.sourceSection },
        evidence: e.evidence,
      })),
      safetyFlags: s.flags.map((f) => ({ code: f.code, severity: f.severity, source: f.source, description: f.description, criterionIds: f.criterionIds, factIds: f.factIds })),
      humanReview: {
        required: s.decision === 'REQUIRES_HUMAN_OVERVIEW',
        tasks: s.reviewTasks.map((t) => ({ id: t.id, status: t.status, reasons: t.reasons, createdAt: t.createdAt.toISOString(), resolvedAt: t.resolvedAt?.toISOString() ?? null })),
        decisions: reviewDecisions.map((d) => ({
          reviewer: d.reviewer.displayName,
          reviewerEmail: d.reviewer.email,
          reviewerRole: d.reviewerRole,
          action: d.action,
          reason: d.reason,
          resultingDecision: d.resultingDecision,
          signedAt: d.createdAt.toISOString(),
          signatureHash: d.signatureHash,
          signatureMeaning: 'Reviewer attests to the action and reason recorded (electronic signature manifestation, demonstration only).',
        })),
      },
      components: {
        ruleEngine: RULE_ENGINE_VERSION,
        ontology: ONTOLOGY_VERSION,
        orchestrator: ORCHESTRATOR_VERSION,
        agentContracts: CONTRACT_VERSION,
        dossierService: DOSSIER_SERVICE_VERSION,
      },
      agents: Object.values(AGENT_DEFINITIONS).map((d) => {
        const ex = executions.filter((x) => x.agentKey === d.key);
        return {
          key: d.key,
          name: d.name,
          version: d.version,
          providers: [...new Set(ex.map((x) => x.provider))],
          agentIds: [...new Set(ex.map((x) => x.agentId).filter(Boolean))],
          executions: ex.map((x) => ({ executionId: x.id, provider: x.provider, status: x.status, latencyMs: x.latencyMs, inputHash: x.inputHash, outputHash: x.outputHash, injectionDetected: x.injectionDetected, at: x.startedAt.toISOString() })),
        };
      }),
      narrative: narrative?.narrative
        ? { authoritative: false, source: narrative.source, summary: narrative.narrative.summary, keyPoints: narrative.narrative.keyPoints }
        : null,
      auditTrail: {
        chainId: s.id,
        algorithm: 'SHA-256 over canonical JSON; each event embeds previousEventHash',
        events: events.map((e) => ({
          sequence: e.sequence,
          eventId: e.id,
          timestamp: e.timestamp,
          eventType: e.eventType,
          actorType: e.actorType,
          actorId: e.actorId,
          component: e.component,
          componentVersion: e.componentVersion,
          inputHash: e.inputHash,
          outputHash: e.outputHash,
          previousEventHash: e.previousEventHash,
          eventHash: e.eventHash,
        })),
        rootHash: verification.rootHash,
        verification: { valid: verification.valid, eventsVerified: verification.eventsVerified, reason: verification.reason ?? null, verifiedAt: new Date().toISOString() },
      },
      disclaimer: DISCLAIMER,
    };
  }

  renderPdf(d: Dossier): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ size: 'A4', margin: 44, bufferPages: true, info: { Title: `TrialGuard AI dossier ${d.screening.ref}`, Author: 'TrialGuard AI (synthetic demo)', Subject: 'FDA-style audit dossier' } });
      const rawText = doc.text.bind(doc);
      (doc as unknown as { text: (...a: unknown[]) => unknown }).text = (t: unknown, ...rest: unknown[]) => rawText(pdfSafe(t), ...(rest as []));
      const chunks: Buffer[] = [];
      doc.on('data', (c: Buffer) => chunks.push(c));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const NAVY = '#0b1f3a';
      const MUTED = '#5b6b82';
      const colors: Record<string, string> = { PASS: '#15803d', FAIL: '#b91c1c', UNKNOWN: '#b45309', NOT_APPLICABLE: '#475569', ELIGIBLE: '#15803d', INELIGIBLE: '#b91c1c', REQUIRES_HUMAN_OVERVIEW: '#b45309' };
      const width = doc.page.width - 88;

      const heading = (t: string) => {
        doc.moveDown(0.6);
        if (doc.y > doc.page.height - 120) doc.addPage();
        doc.fillColor(NAVY).font('Helvetica-Bold').fontSize(12).text(t.toUpperCase());
        doc.moveTo(44, doc.y + 2).lineTo(44 + width, doc.y + 2).strokeColor('#cbd5e1').lineWidth(0.7).stroke();
        doc.moveDown(0.4);
      };
      const kv = (k: string, v: unknown) => {
        doc.font('Helvetica-Bold').fontSize(8.5).fillColor(MUTED).text(`${k}: `, { continued: true });
        doc.font('Helvetica').fillColor('#111827').text(v === null || v === undefined ? '—' : String(v));
      };
      const mono = (t: string) => doc.font('Courier').fontSize(7.2).fillColor('#334155').text(t);

      // Header band
      doc.rect(0, 0, doc.page.width, 78).fill(NAVY);
      doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(18).text('TrialGuard AI', 44, 20);
      doc.font('Helvetica').fontSize(9.5).fillColor('#bfdbfe').text('FDA-style audit dossier · Part-11-oriented audit controls · SYNTHETIC DEMONSTRATION DATA', 44, 44);
      doc.fillColor('#fbbf24').fontSize(8).text('Not FDA approved · not clinically validated · not for direct clinical decision-making', 44, 58);
      doc.y = 96;

      const decision = String(d.decision.finalDecision ?? 'PENDING');
      doc.roundedRect(44, doc.y, width, 46, 4).fill('#f1f5f9');
      doc.fillColor(colors[decision] ?? NAVY).font('Helvetica-Bold').fontSize(16).text(decision.replace(/_/g, ' '), 56, doc.y + 8);
      doc.fillColor(MUTED).font('Helvetica').fontSize(8.5).text(
        `Screening ${d.screening.ref} · ${d.patient.patientRef} · ${d.trial.code} · confidence ${d.decision.confidencePct ?? '—'}% · decided by ${d.decision.decidedBy}`,
        56,
        doc.y + 2,
      );
      doc.y += 22;

      heading('1. Trial and protocol');
      kv('Trial', `${d.trial.code} — ${d.trial.title}`);
      kv('Phase / sponsor', `${d.trial.phase} / ${d.trial.sponsor}`);
      kv('Protocol version', d.protocol.version);
      kv('Protocol SHA-256', d.protocol.contentHash);
      kv('Redacted protocol SHA-256', d.protocol.redactedHash);
      kv('Criteria extracted', `${d.protocol.criteria} (ambiguous: ${d.protocol.ambiguousCriteria.join(', ') || 'none'})`);
      kv('Protocol extraction audit root', d.protocol.extractionAuditRoot);
      const pcv = d.protocol.crossValidation as { agreementRate: number; agreed: string[]; resolved: Array<{ id: string }>; recovered: string[]; llmOnly: string[] } | null;
      kv('Criteria cross-validation (LLM vs deterministic)', pcv ? `${Math.round(pcv.agreementRate * 100)}% agreement; ${pcv.agreed.length} agreed, ${pcv.resolved.length} resolved deterministically (${pcv.resolved.map((r) => r.id).join(', ') || 'none'}), ${pcv.recovered.length} recovered, ${pcv.llmOnly.length} LLM-only` : 'not applicable (mock simulator)');

      heading('2. Patient reference and PHI protection');
      kv('Patient reference', `${d.patient.patientRef} (synthetic)`);
      kv('Patient snapshot SHA-256', d.patient.snapshotHash);
      const fcv = d.patient.crossValidation as { agreementRate: number; agreed: string[]; resolved: unknown[]; recovered: unknown[]; llmOnly: unknown[] } | null;
      kv('Facts cross-validation (LLM vs deterministic)', fcv ? `${Math.round(fcv.agreementRate * 100)}% agreement; ${fcv.agreed.length} agreed, ${fcv.resolved.length} resolved, ${fcv.recovered.length} recovered, ${fcv.llmOnly.length} LLM-only` : 'not applicable (mock simulator)');
      kv('PHI redactions before inference', `${d.phiRedaction.totalRedactions} — ${Object.entries(d.phiRedaction.byCategory).map(([k, v]) => `${k}: ${v}`).join(', ') || 'none'}`);
      doc.font('Helvetica').fontSize(8).fillColor('#111827').text(d.phiRedaction.statement, { width });

      heading('3. Decision');
      kv('System decision (deterministic)', d.decision.systemDecision);
      kv('Final decision', d.decision.finalDecision);
      kv('Confidence', `${d.decision.confidencePct}%`);
      const bd = d.decision.confidenceBreakdown as { criterionMean?: number; safetyPenalty?: number; formula?: string } | null;
      if (bd) kv('Confidence calculation', `criterion mean ${bd.criterionMean} − safety penalty ${bd.safetyPenalty}. ${bd.formula}`);
      for (const r of (d.decision.reasons as string[] | null) ?? []) doc.font('Helvetica').fontSize(8).fillColor('#111827').text(`• ${r}`, { width });

      heading('4. Criterion evaluations');
      for (const e of d.criterionEvaluations) {
        if (doc.y > doc.page.height - 110) doc.addPage();
        const y = doc.y;
        doc.font('Helvetica-Bold').fontSize(8.8).fillColor(colors[e.result] ?? NAVY).text(e.result === 'NOT_APPLICABLE' ? 'N/A' : `${e.result}`, 44, y, { width: 70 });
        doc.font('Helvetica-Bold').fillColor(NAVY).text(`${e.criterionId} · ${e.category}${e.mandatory ? '' : ' (non-binding)'} · p.${e.protocolSource.page}`, 116, y, { width: width - 72 });
        doc.font('Helvetica').fontSize(7.8).fillColor('#111827').text(e.requirement, 116, doc.y, { width: width - 72 });
        doc.fillColor(MUTED).text(`Expected: ${e.expectedValue}`, { width: width - 72 });
        doc.text(`Actual: ${e.actualValue ?? '—'}`, { width: width - 72 });
        doc.font('Courier').fontSize(7.2).fillColor('#334155').text(`Rule: ${e.ruleExpression}`, { width: width - 72 });
        const ev = (e.evidence as Array<{ factId: string; sourceDocument: string; page: number; observedAt: string | null }>) ?? [];
        if (ev.length) doc.font('Helvetica').fontSize(7.2).fillColor(MUTED).text(`Evidence: ${ev.map((x) => `${x.factId} (${x.sourceDocument} p.${x.page}${x.observedAt ? `, ${x.observedAt}` : ''})`).join('; ')}`, { width: width - 72 });
        doc.font('Helvetica').fontSize(7.6).fillColor('#111827').text(`Reason: ${e.reason}`, { width: width - 72 });
        doc.x = 44;
        doc.moveDown(0.45);
      }

      heading('5. Safety flags');
      if (!d.safetyFlags.length) doc.font('Helvetica').fontSize(8.5).fillColor('#111827').text('None.');
      for (const f of d.safetyFlags) doc.font('Helvetica').fontSize(8).fillColor(f.severity === 'BLOCKING' ? '#b91c1c' : f.severity === 'WARNING' ? '#b45309' : MUTED).text(`[${f.severity}] ${f.code} (${f.source}) — ${f.description}`, { width });

      heading('6. Human review');
      kv('Human review required', d.humanReview.required ? 'yes' : 'no');
      for (const t of d.humanReview.tasks) kv(`Task ${t.id.slice(0, 8)}`, `${t.status} (created ${t.createdAt})`);
      for (const r of d.humanReview.decisions) {
        doc.font('Helvetica').fontSize(8).fillColor('#111827').text(`• ${r.signedAt} — ${r.reviewer} (${r.reviewerRole}): ${r.action} → ${r.resultingDecision ?? 'no final decision'}. Reason: "${r.reason}"`, { width });
        mono(`  signature ${r.signatureHash}`);
      }
      if (!d.humanReview.decisions.length) doc.font('Helvetica').fontSize(8).fillColor(MUTED).text('No reviewer decisions recorded.');

      heading('7. Components and agents');
      for (const [k, v] of Object.entries(d.components)) kv(k, v);
      for (const a of d.agents) kv(`${a.name} v${a.version}`, `${a.executions.length} execution(s); provider ${a.providers.join(', ') || 'n/a'}${a.agentIds.length ? `; Lyzr agent ${a.agentIds.join(', ')}` : ''}`);

      if (d.narrative) {
        heading('8. Narrative (AI-generated, non-authoritative)');
        doc.font('Helvetica-Oblique').fontSize(8.2).fillColor('#111827').text(d.narrative.summary, { width });
        doc.font('Helvetica').fontSize(7.5).fillColor(MUTED).text(`Source: ${d.narrative.source}. Critical fields above are rendered from application data, not from this narrative.`, { width });
      }

      heading('9. Audit timeline and hash chain');
      kv('Chain id', d.auditTrail.chainId);
      kv('Algorithm', d.auditTrail.algorithm);
      kv('Root hash', d.auditTrail.rootHash);
      kv('Verification', `${d.auditTrail.verification.valid ? 'VALID' : 'INVALID'} — ${d.auditTrail.verification.eventsVerified} events verified at ${d.auditTrail.verification.verifiedAt}`);
      doc.moveDown(0.3);
      for (const e of d.auditTrail.events) {
        if (doc.y > doc.page.height - 70) doc.addPage();
        mono(`#${String(e.sequence).padStart(3, '0')} ${e.timestamp} ${e.eventType.padEnd(28)} ${e.actorType.padEnd(6)} ${e.component} v${e.componentVersion}`);
        mono(`     hash ${e.eventHash}  prev ${e.previousEventHash.slice(0, 16)}…`);
      }

      heading('Disclaimer');
      doc.font('Helvetica').fontSize(8).fillColor('#111827').text(d.disclaimer, { width });

      const range = doc.bufferedPageRange();
      for (let i = range.start; i < range.start + range.count; i++) {
        doc.switchToPage(i);
        doc.font('Helvetica').fontSize(7).fillColor(MUTED).text(
          `${d.screening.ref} · SYNTHETIC DATA · root ${String(d.auditTrail.rootHash).slice(0, 16)}… · page ${i + 1} of ${range.count}`,
          44,
          doc.page.height - 30,
          { width, align: 'center', lineBreak: false },
        );
      }
      doc.end();
    });
  }

  /** Generate, store and register a new dossier version (JSON + PDF). */
  async generate(screeningId: string) {
    const json = await this.buildJson(screeningId);
    const pdf = await this.renderPdf(json);
    const version = (await this.prisma.auditDossier.count({ where: { screeningId } })) + 1;
    const jsonBuf = Buffer.from(JSON.stringify(json, null, 2), 'utf8');
    const j = await this.storage.put(`dossiers/${screeningId}/v${version}.json`, jsonBuf, { encrypt: false });
    const p = await this.storage.put(`dossiers/${screeningId}/v${version}.pdf`, pdf, { encrypt: false });
    const row = await this.prisma.auditDossier.create({
      data: { screeningId, version, jsonHash: j.sha256, pdfHash: p.sha256, jsonStorageKey: j.key, pdfStorageKey: p.key, auditRootHash: json.auditTrail.rootHash ?? '', chainValid: json.auditTrail.verification.valid },
    });
    await this.audit.append(screeningId, {
      eventType: 'DOSSIER_GENERATED',
      actorType: 'SYSTEM',
      component: 'dossier-service',
      componentVersion: DOSSIER_SERVICE_VERSION,
      input: { auditRootHash: json.auditTrail.rootHash },
      output: { jsonHash: j.sha256, pdfHash: p.sha256 },
      payload: { version, jsonSha256: j.sha256, pdfSha256: p.sha256, coveredRootHash: json.auditTrail.rootHash, contentHash: hashObject({ ...json, generatedAt: undefined }) },
    });
    return { row, json, pdf };
  }

  /**
   * Latest dossier file. If the stored file is gone (e.g. an ephemeral
   * container disk was wiped by a redeploy) the dossier is regenerated from
   * the database — it is built only from stored application data, so no agent
   * call is made — and the regeneration is recorded in the audit chain.
   */
  async latest(screeningId: string, kind: 'json' | 'pdf'): Promise<{ buffer: Buffer; version: number; sha256: string }> {
    const row = await this.prisma.auditDossier.findFirst({ where: { screeningId }, orderBy: { version: 'desc' } });
    if (row) {
      try {
        const buffer = await this.storage.get(kind === 'json' ? row.jsonStorageKey : row.pdfStorageKey, { encrypted: false });
        return { buffer, version: row.version, sha256: sha256Hex(buffer) };
      } catch (err) {
        if ((err as NodeJS.ErrnoException).code !== 'ENOENT') throw err;
      }
    }
    const fresh = await this.generate(screeningId);
    const buffer = kind === 'json' ? Buffer.from(JSON.stringify(fresh.json, null, 2), 'utf8') : fresh.pdf;
    return { buffer, version: fresh.row.version, sha256: sha256Hex(buffer) };
  }
}
